### PR TITLE
Runnable on iOS.

### PR DESCRIPTION
**Pull request by izambasiron**
Android need some more work.

### CODE REVIEW

**Comment by lejard-h** [comment]
nice, I will review this weekend.

Can you explain what is missing for Android ?

**Comment by izambasiron** [comment]
Yes, for Android, it launches a black screen then minimize itself to the background. There's no error being thrown. I haven't had time to look at it in detail. 

Here's a video:
android-flitter-hide

**Comment by izambasiron** [comment]
Had a quick look at Android and luckily it wasn't too hard to fix. But now that I know how the app actually looks, I realize iOS wasn't working as expected after all. 😅 

| iOS | Android |
| --- | --- |
| iOS | Android |

**Comment by izambasiron** [comment]
Fixed iOS issue.

**Review by lejard-h — APPROVED** [review]

**Comment by lejard-h** [comment]
Works well,
thanks you :/

**Pull request merged**
